bend-platform:
    database:
        database-type: POSTGRESQL
        host: localhost
        schema: bend-platform-test
        username: lemon
        password: lemon
        driver: org.postgresql.Driver
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQL82Dialect
