#Enabled All Facilities for development, Testing & Debugging

spring:
    profiles:
        include: postgre, liquibase, api-docs

bend-platform:
    settings:
        security:
            secret-key: ZDc4MzUyZjZjOGM2MTkzNjE1N2JjOTc0MzhiNGFkMGNlNTA0MzQ0YTJkMTVhM2JkMjI5NGIwM2Y4OGU4NjIxM2JmNTA4ZTg3YjI3ZDJiZGQwYzNmZmJhN2NjYTQ1NTllODNmOTJjOWNhODkzNDI1ZDFmYzkzMWEzYWYyMGZhNjA=
            session-live-time: 20F
            account:
                password:
                    recoverable: true
                    recovery-timeout-minutes: 5
                    recovery-code-length: 8
            authentication:
                maximum-live-session-count: 5
                maximum-login-limit-in-day: 20
                maximum-live-session-from-same-ip: 3
                maximum-login-limit-in-month: 140
                maximum-request-per-session: 2000
                maximum-live-session-in-one-ip: 6
                jwt:
                    secret: ZDc4MzUyZjZjOGM2MTkzNjE1N2JjOTc0MzhiNGFkMGNlNTA0MzQ0YTJkMTVhM2JkMjI5NGIwM2Y4OGU4NjIxM2JmNTA4ZTg3YjI3ZDJiZGQwYzNmZmJhN2NjYTQ1NTllODNmOTJjOWNhODkzNDI1ZDFmYzkzMWEzYWYyMGZhNjA=
                    base64-secret: ZDc4MzUyZjZjOGM2MTkzNjE1N2JjOTc0MzhiNGFkMGNlNTA0MzQ0YTJkMTVhM2JkMjI5NGIwM2Y4OGU4NjIxM2JmNTA4ZTg3YjI3ZDJiZGQwYzNmZmJhN2NjYTQ1NTllODNmOTJjOWNhODkzNDI1ZDFmYzkzMWEzYWYyMGZhNjA=
                    token-validity-in-seconds: 3600
                    token-validity-in-seconds-for-remember-me: 7200
                    token-store-database:

            secure-channel:
                - dev
                - console
            cors:
                allowed-clients:
                    - http://tomcat-host:8080
            public-servlet-prefixes:
                - /api/public
        mail:
            host: smtp.gmail.com
            port: 587
            username: springboottest420@gmail.com
            password: springboottest42kblkbl
            protocol: smtp
            debug: true
            smtp:
                auth: true
                starttls-enable: true
                ssl-trust: smtp.gmail.com
        async:
            core-pool-size: 8
            max-pool-size: 50
            queue-capacity: 1000
            thread-name-prefix: spring-prod
    database:
        liquibase-type: create
        maximum-active-connection-size: 200
        max-idle-connection-size: 100
        min-idle-connection-size: 20
        hibernate:
            hbm2-ddl-auto: none
            format-sql: false
            comments: false
            show-sql: false
            enable-second-level-cache: true
            enable-strutured-cache: true
            enable-auto-evict-coll-cache: true
            enable-query-cache: true
            annotated-packages:
                - bend.library.domain.entity
                - bend.library.domain.cluster.entity
        jpa:
            persistent-unit: SPRING
            repository-locations:
                - bend.library.domain.repositories
                - bend.library.domain.cluster.repositories
    cache:
        eh-cache:
            max-local-heap-size: 20M
