bend-platform:
    settings:
        general:
            name: Bend-Main-App
    database:
        hibernate:
            annotated-packages:
                - bend.library.domain.entity
                - bend.library.domain.cluster.entity
        jpa:
            repository-locations:
                - bend.library.domain.repositories
                - bend.library.domain.cluster.repositories

spring:
    profiles:
        active: dev
    liquibase:
        enabled: true
    flyway:
        enabled: false
server:
    port: 8787
    servlet:
        context-path: /bend-main-app

eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/