
bend-platform:
    database:
        database-type: POSTGRESQL
        url: jdbc:postgresql://localhost:5432/bend-platform
        schema: spring
        username: lemon
        password: lemon
        driver: org.postgresql.Driver
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQL82Dialect
