
bend-platform:
    database:
        database-type: POSTGRESQL
        host: 192.168.0.104
        schema: bend-platform
        username: lemon
        password: lemon
        driver: org.postgresql.Driver
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQL82Dialect
