

bend-platform:
  settings:
      general:
          name: Spring-Boot-Service-Registry
spring:
    profiles:
        active: dev
server:
    port: 8789
    servlet:
        context-path: /bend-service-registry
