bend-platform:
    settings:
        general:
            name: Bend-Gateway
        security:
            cors:
                active: true
                allowed-clients: [http://localhost:4200]
server:
    port: 8788
spring:
    profiles:
        include: zuul

info:
    app:
        name: Bend-Gateway
        description: Bend-Platform-Application[Microservice-Gateway]. A Highly Scallable Microservice Application.
        version: 1.0.2-microservice
