zuul:
    ignored-services: '*'
    prefix: /api
    routes:
        bend-main-app:
            path: /bend-main-app/**/*
            service-id: bend-main-app
            strip-prefix: false
        bend-ficket-app:
            path: /bend-ficket-app/**/*
            service-id: bend-ficket-app
            strip-prefix: false
    sensitive-headers: [Cookie, Set-Cookie]

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeout-in-milliseconds: 60000
