bend-platform:
    settings:
        general:
            name: Bend-Service-Registry
        security:
            secure-channel:
                - dev
                - console
            cors:
                allowed-clients:
                    - http://localhost:4200
                    - http://192.168.1.43:4200
                    - http://192.168.0.154:4200
                    - http://192.168.0.153:4200
            public-servlet-prefixes:
                - /public
server:
    port: 8761
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
    dashboard:
        path: /eurekawebui
