

bend-platform:
  settings:
      general:
          name: Spring-Boot-Service-Registry
server:
    port: 8761
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
    dashboard:
        path: /eurekawebui