bend-platform:
    settings:
        general:
            name: Bend-Service-Registry
        security:
            secure-channel:
                - dev
                - console
            cors:
                active: false
server:
    port: 8761
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
    dashboard:
        path: /eurekawebui
