

bend-platform:
  settings:
      general:
          name: Spring-Boot-Service-Registry
server:
    port: 8761
    servlet:
        context-path: /bend-service-registry
eureka:
  dashboard:
    path: /eurekawebui