bend-platform:
    settings:
        security:
            secure-channel:
                - dev
                - console
            cors:
                active: false
                allowed-clients: [http://localhost:4200]
                allowed-headers: [Authorization, Accept, Content-Type, Origin, Access-Control-Allow-Origin, Access-Control-Allow-Headers, X-Requested-With, Cache-Control, User-Agent, Accept-Encoding, Connection, Host]
                exposed-headers: [Json-Web-Token, Refreshed-Json-Web-Token, Accept, Content-Type, Origin]
eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/

spring:
    profiles:
        include: dev